### ISSUE TITLE
Sample site configuration and templates

### ISSUE THREAD

**Issue by kafana** [clay/clay#7]
Is there an example/demo site that will help me bootstrap basic amphora/kiln configuration? I'm looking for a sample of layouts, components, and sites directories with corresponding templates and schema files. Can you point me to a repository or page that contains this data? I'm trying to put together a basic site using amphora and kiln, but it is taking lots of trial and error using docs that are scattered across multiple repositories. Basically, I'm looking for a more complete documentation with a running sample site. 

Also, I'm not sure if this question belongs to issues, but couldn't find a better place place to post it. Feel free to close this and point me to a right location.

**Comment by kafana** [comment]
@jonwinton That's great news! I won't need anything fancy, just a basic skeleton of a typical clay project, with a couple of pages, components and layouts. I think It should be pretty straight forward to build an additional configuration on the top of this, but if get stuck I'll definitely take you up on your offer :)

**Comment by jonwinton** [comment]
@kafana so sorry for the delay, things got a little busy on our end.

That being said, here's the demo to kick around: https://github.com/clay/clay-starter

Our goal is to move all development of the open-source modules to this environment so that it grows in serves as an example for different approaches to be taken with Clay components. The components themselves are also going to be up for grabs and will be maintained.

Hope it helps!

**Comment by kafana** [comment]
@jonwinton This is exactly what I had in mind. I'll let you know if I run into into any problems. Thank you!

**Comment by jonwinton** [comment]
I'm going to close this issue but feel free to open up any other issues in that repo if you find anything.
